[project]
name = "dl-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "torch",
    "transformers",
    "sentencepiece",
    "protobuf>=6.33.1",
]
